# Generated by Django 4.2.7 on 2026-01-18 07:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards', '0002_reward_userreward'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userreward',
            name='unique_user_reward',
        ),
        migrations.RenameIndex(
            model_name='userreward',
            new_name='rewards_use_user_id_802b81_idx',
            old_name='rewards_use_user_id_earned_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userreward',
            unique_together={('user', 'reward')},
        ),
    ]
