# Generated by Django 4.2.7 on 2026-01-17 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Question text/prompt')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=10)),
                ('explanation', models.TextField(blank=True, help_text='Optional explanation of the correct answer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quiz_question',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Option text')),
                ('is_correct', models.BooleanField(default=False, help_text='Mark the correct answer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0-3)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question')),
            ],
            options={
                'db_table': 'quiz_question_option',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('total_questions', models.PositiveIntegerField(default=15)),
                ('answered_questions', models.PositiveIntegerField(default=0, help_text='Number of questions answered')),
                ('unanswered_questions', models.PositiveIntegerField(default=0, help_text='Number of questions left unanswered')),
                ('correct_answers', models.PositiveIntegerField(default=0, help_text='Number of correct answers')),
                ('incorrect_answers', models.PositiveIntegerField(default=0, help_text='Number of incorrect answers')),
                ('total_score', models.PositiveIntegerField(default=0, help_text='Total points earned (sum of correct answers)')),
                ('max_score', models.PositiveIntegerField(default=0, help_text='Maximum possible score for this test')),
                ('percentage', models.FloatField(default=0.0, help_text='Percentage score (0-100)')),
                ('earned_points', models.PositiveIntegerField(default=0, help_text='Reward points earned from this test')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, help_text='Time taken to complete the test in seconds', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_test_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('is_unanswered', models.BooleanField(default=True, help_text='True if question was not answered')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('selected_option', models.ForeignKey(blank=True, help_text='The option user selected (null if unanswered)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.questionoption')),
            ],
            options={
                'db_table': 'quiz_test_response',
                'ordering': ['answered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='quiz_questi_difficu_fde0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='testresponse',
            index=models.Index(fields=['attempt', 'question'], name='quiz_test_r_attempt_c02fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='testresponse',
            index=models.Index(fields=['is_unanswered'], name='quiz_test_r_is_unan_36eaf6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testresponse',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', '-started_at'], name='quiz_test_a_user_id_024e9e_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['difficulty'], name='quiz_test_a_difficu_d541bd_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['is_completed'], name='quiz_test_a_is_comp_f3a807_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question'], name='quiz_questi_questio_9c88fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionoption',
            unique_together={('question', 'order')},
        ),
    ]
